name: First job
on: push

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests IPython pytest
      - name: Run tests
        run: pytest -v .
